import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-89v flex flex-col items-center justify-center">
        <h1 className=" text-7xl font-bold">Welcome</h1>
        <p className=" w-96 p-3 mt-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Et
          consequatur tempore animi. Eum at expedita assumenda, soluta sint ut
          ipsam deleniti omnis, non laborum enim incidunt laboriosam itaque amet
          aperiam.
        </p>
      </div>
    </div>
  );
}
